export const ROOT_URL = "http://localhost:52176";
export const LOAD_PETTYPES_BEGIN = 'LOAD_PETTYPES_BEGIN';
export const LOAD_PETTYPES_SUCCESS = 'LOAD_PETTYPES_SUCCESS';
export const LOAD_PETTYPES_FAIL ="LOAD_PETTYPES_FAIL";

export const ACTION_VALIDATE_USERNAME = 'ACTION_VALIDATE_USERNAME';
export const ACTION_VALIDATE_USERNAME_BEGIN = 'ACTION_VALIDATE_USERNAME_BEGIN';
export const ACTION_VALIDATE_USERNAME_SUCCESS = 'ACTION_VALIDATE_USERNAME_SUCCESS';
export const ACTION_VALIDATE_USERNAME_FAIL = 'ACTION_VALIDATE_USERNAME_FAIL';

export const ACTION_VALIDATE_EMAIL = 'ACTION_VALIDATE_EMAIL';
export const ACTION_VALIDATE_EMAIL_BEGIN = 'ACTION_VALIDA_EMAIL_BEGIN';
export const ACTION_VALIDATE_EMAIL_SUCCESS = 'ACTION_VALIDATE_EMAIL_SUCCESS';
export const ACTION_VALIDATE_EMAIL_FAIL = 'ACTION_VALIDATE_EMAIL_FAIL';

export const ACTION_CREATE_ACCOUNT = 'ACTION_CREATE_ACCOUNT';
export const ACTION_CREATE_ACCOUNT_BEGIN = 'ACTION_CREATE_ACCOUNT_BEGIN';
export const ACTION_CREATE_ACCOUNT_SUCCESS = 'ACTION_CREATE_ACCOUNT_SUCCESS';
export const ACTION_CREATE_ACCOUNT_FAIL = 'ACTION_CREATE_ACCOUNT_FAIL';